project:
  type: website

website:
  title: "./datasolidarity-community.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

