project:
  type: website

website:
  title: "Data Solidarity"
  search: false
  navbar:
    title: false
    pinned: false
    collapse-below: md
  sidebar:
    logo: logo-zorginstituut.png
    style: docked  
    collapse-level: 1
    background: light
    contents:
      - text: "Register | Inschrijven"
        href: register.qmd
      - text: "Read more | Lees meer"
        href: more.qmd
      - text: "About | Over"
        href: about.qmd
format:
  html:
    page-layout: full
    date-format: "MMM YYYY"
    theme:
      light:
        - flatly
        - mozilla.scss
    css: styles.css
    toc: false

execute: 
  freeze: auto


