---
title: "About"
---

The National Health Care Institute (NHCI) is one of the key public institutions tasked with overseeing the national healthcare system in the Netherlands. Its core responsibilities include:

- advising the Ministry of Health on the scope of the basic health insurance package;
- promoting the quality, affordability and accessibility of care;
- developing information standards; encourage utilisation of digital health;
- managing the funds for the Health Insurance Act and the Long-term Care Act;
- manage risk adjustment in the care sector.

In line with these responsibilities, the NHCI has launched a programme "Datalogica" to explore various areas related to digital health. Already in 2020 the idea of 'data solidarity' was discussed in one of the projects. A report by the Rathenau Institute from 2020 also explored the concept of data solidarity, defining it as "... performing research on data that has already been collected" and "... research that does not fall under the Wet Medisch Onderzoek op mensen". The report explores aspects for the three key actors, the patient, the care professional and the researcher.

Since these first conceptions of data solidarity, quite a lot has happened. Key acts from the European strategy for data are now in place, including the Data Governance Act (DGA, applicable since September 2023), the Data Act (entered into force January 2024), the AI Act (passed EU Parliament May 2024) and the upcoming legislation on European Health Data Spaces. The public debate on the “ethics of sharing” health data continues to divide or at least confuse the general public and professionals alike. Meanwhile, technical developments in the area of federated learning (FL) and secure multiparty computation (MPC) hint at new solution designs that may be able to remedy the tensions and barriers that stand in the way of wide-scale reuse of data.

It is within this context that the NHCI has initiated a research project, positioned within the Datalogica programme, to explore conceptualization and operationalisation of data solidarity for the Dutch health care sector in which the different perspectives are integrated. Besides the content and deliverable of this research project, a secondary aim is to initiate a wider discussion, first within NHCI and ultimately reaching out to stakeholders in the Netherlands and Europe, to have a meaningful and practical debate on new perspectives on solidarity for the information age.

Project Team:
- Teresa Cardoso Ribeiro - van den Muijzenberg (NCHI Project lead)
- Daniel Kapitan
- Egge van der Poel (contact info@eggewel.nl) 
